spring:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

# Flyway Configuration
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    locations: classpath:db/migration
    user: postgres
    password: postgres
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: cart
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

axon:
  serializer:
    ## xstream is not compatible anymore with jdk17+
    general: jackson
  axonserver:
    enabled: false

application:
  debug:
    enabled: true
